### ISSUE TITLE
Getting in touch with you!

### ISSUE THREAD

**Issue by Sensei85** [petter-ka/youpez-admin#3]
Hey Petter, love your work here. I don't have an issue but I find it's the only way I could contact you. I'd like us to make a port of this admin in svelte and sveltekit. I have started and got carbon components working in sveltekit. If it's something you'd be interested in kindly hit me up on twitter via link in my bio. Nice work here bro, Cheers.

**Comment by petter-ka** [comment]
Hi Sensei85,

I'm glad you found this admin template inspiring/useful. I will look forward for your svelte version! Thanks for your nice comment. Cheers
